server:
  port: 8082  # Configures the port where the Spring Boot application (API Gateway) will run. In this case, the gateway will be accessible at port 8082.

jwt:
  secret: jbdgasdgasdgasudgaosdgaodgaosdgasdfdsfsfsddoiasgdoaisdhoadoasdasda

spring:
  application:
    name: api-gateway  # Sets the application name as 'api-gateway'. This is useful for logging, service discovery (Eureka), and identifying the service.

  cloud:
    gateway:
      routes:  # Defines the routes for the Spring Cloud Gateway
        - id: order-service  # The identifier for the route. It is used to uniquely identify the route.
          uri: lb://ORDER-SERVICE  # Load-balanced URI to forward requests to the 'ORDER-SERVICE'.
          # The 'lb://' prefix tells the gateway to use load balancing and Eureka for service discovery.
          predicates:  # Conditions (predicates) that must be met for this route to be used.
            - Path=/orders/**  # This route will be used for any requests with the path starting with '/orders/'.
          filters:
            - name: LoggingOrderFilter  # Use 'filters' section, not 'name'
            - name: Authentication
              args:
                isEnabled: true
            - name: Authorization
              args:
                roles:
                  - ADMIN
                  - SUPER_ADMIN
#                isEnabled: true
        #            - Path=/api/v1/orders/**  # This line is commented out. If enabled, it would route requests with '/api/v1/orders/**' to the order service.
#          filters:
#            - StripPrefix=2  # This will remove the first 2 path segments. For example, '/orders/123' becomes '/123'.


        - id: inventory-service  # The identifier for another route, this time for the inventory service.
          uri: lb://INVENTORY-SERVICE  # Load-balanced URI to forward requests to the 'INVENTORY-SERVICE' using Eureka for service discovery.
          predicates:  # Conditions for the inventory route.
            - Path=/inventory/**  # This route will be used for any requests with the path starting with '/inventory/'.

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # Specifies the location of the Eureka server. This is where the gateway will look for available services (Order Service, Inventory Service, etc.).
